version: '3'
services:
  lint-format:
    container_name: lint-format
    image: lint-format
    build:
      context: ./lint-fmt/
    volumes:
      - .:/lint-fmt
    environment:
      - FRONTEND_DIR=./frontend
      - TOML_FILE=./backend/Cargo.toml