services:
  app:
    container_name: app
    image: app
    build:
      context: ./app/
    init: true
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_ROOT=./project/app/src/app
      - BACKEND_ROOT=./project/programs/project/src