services:
  app:
    container_name: app
    image: app
    build:
      context: ./app/
      dockerfile: build_tool/Dockerfile
    init: true
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
      - "8899:8899"
      - "8900:8900"
    environment:
      - FRONTEND_ROOT=./project/app/src/app
      - BACKEND_ROOT=./project/programs/project/src

  lint-format:
    container_name: lint-format
    image: lint-format
    build:
      context: ./app/
      dockerfile: debug_tool/Dockerfile
    volumes:
      - .:/lint-fmt
    environment:
      - FRONTEND_DIR=./frontend
      - TOML_FILE=./backend/Cargo.toml