name: Build Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build-ubuntu:
    if: github.event.pull_request.draft == false
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run make (Ubuntu)
      run: make

  build-arm:
    if: github.event.pull_request.draft == false
    name: Build on ARM
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU for ARM
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm64,linux/arm/v7

    - name: Run make (ARM)
      run: make

name: Build Test
