name: Build and Test ARM with Docker Compose

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build-arm:
    if: github.event.pull_request.draft == false
    name: Build on ARM with Docker Compose
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm64

    - name: Build and Test with Docker Compose
      run: make
