name: Build Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build-macos:
    if: github.event.pull_request.draft == false
    name: Build on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run make (macOS)
      run: make

  build-ubuntu:
    if: github.event.pull_request.draft == false
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run make (Ubuntu)
      run: make
