name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build-ubuntu:
    if: github.event.pull_request.draft == false
    name: Build and Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run make test-anchor (Ubuntu)
      run: make test-anchor
